dist: trusty
language: java
jdk:
   - oraclejdk8
script:
   - git clone https://github.com/javapathfinder/jpf-core.git wikumC/jpf-core
   - cd wikumC/jpf-core
   - ./gradlew buildjars
   - cd ..
   - ls
   
   
addons:
  apt:
    packages:
      - oracle-java8-installer
      
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
