dist: bionic

language: java

jdk:
   - openjdk8

script:
   - cd ..
   - git clone https://github.com/javapathfinder/jpf-core.git
   - cd jpf-core
   - ./gradlew buildjars
   - cd ../jpf-symbc
   - ant clean build   
      
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
